modules/admin/controllers/AppAdminController.php
<?php


namespace app\modules\admin\controllers;

use yii\base\DynamicModel;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use Yii;
use yii\web\UploadedFile;
use yii\web\Response;
use yii\helpers\FileHelper;
use vova07\imperavi\actions\GetAction;
use yii\image\drivers\Image;
use yii\filters\VerbFilter;

class AppAdminController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'save-redactor-img' => ['POST'],
                ],
            ],
        ];
    }

    // метод для виджета yurkinx/yii2-image, сохраняет картинку
    public function actionSaveRedactorImg($sub = 'imperavi')
    {
        $this->enableCsrfValidation = false;
        if (Yii::$app->request->isPost) {
            $dir = Yii::getAlias('@uploads') . '/' . $sub . '/';
            if (!file_exists($dir)) {
                FileHelper::createDirectory($dir);
            }
            $resultLink = str_replace('admin', '', Url::Home(true) . 'web/uploads/' . $sub . '/');
            $file = UploadedFile::getInstanceByName('file');
            $model = new DynamicModel(compact('file'));
            $model->addRule('file', 'image')->validate();

            if ($model->hasErrors()) {
                $result = [
                    'error' => $model->getFirstError('file')
                ];
            } else {
                $model->file->name = rand(0, 9999) . "-" . date('YmdHi', time()) . '.' . $model->file->extension;
                if ($model->file->saveAs($dir . $model->file->name)) {
                    $image = Yii::$app->image->load($dir.$model->file->name);
//                    $image->resize(800,null, Image::PRECISE)
//                    ->save($dir.$model->file->name,85);// 800 ширина и как получится по высоте, качество 85 %
                    $image->background('#fff',0); // фон картинки
                    $image->resize('475','320',Yii\image\drivers\Image::INVERSE); // если 200x100 то получит 100x50
                    $image->crop('475','320'); // обрезаем
                    $image->save($dir.$model->file->name,100);
                    $result = ['filelink' => $resultLink . $model->file->name,
                        'filename' => $model->file->name];
                } else {
                    $result = [
                        'error' => 'Невозможно загрузить файл'
                    ];
                }
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $result;
        } else {
            throw new BadRequestHttpException('Only Post is allower');
        }
    }


    // необходими решить проблему для удаления картинок из визуального редактора и из сервера

    //для визуального редактора
    public function actions()
    {
        return [
            //для вставки уже загруженных изображений
            'images-get' => [
                'class' => 'vova07\imperavi\actions\GetAction',
                'url' => '/web/uploads/imperavi/', // URL адрес папки где хранятся изображения.
                'path' => Yii::getAlias('@uploads') . '/imperavi', // Или абсолютный путь к папке с изображениями.
                'type' => GetAction::TYPE_IMAGES,
            ],

        ];
    }

}

modules/admin/controllers/ArticleController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Article;
use app\models\ArticleSearch;
use yii\base\DynamicModel;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadImage;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use yii\helpers\Url;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends AppAdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModelArticle = new ArticleSearch();
        $modelArticle = new Article();
        $uploadImageArticle = new UploadImage();
        $dataProviderArticle = $searchModelArticle->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModelArticle' => $searchModelArticle,
            'dataProviderArticle' => $dataProviderArticle,
            'modelArticle' => $modelArticle,
            'uploadImageArticle' => $uploadImageArticle,
            'openFormArticle' => false,
        ]);
    }

//    /**
//     * Displays a single Article model.
//     * @param integer $id
//     * @return mixed
//     */
//    public function actionView($id)
//    {
//        return $this->render('view', [
//            'model' => $this->findModel($id),
//        ]);
//    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelArticle = new Article();
        $uploadImageArticle = new UploadImage();
        $searchModelArticle = new ArticleSearch();
        $dataProviderArticle = $searchModelArticle->search(Yii::$app->request->queryParams);


        if ($modelArticle->load(Yii::$app->request->post())) {
            $uploadImageArticle->image = UploadedFile::getInstance($uploadImageArticle, 'image');
//            var_dump($uploadImageArticle->image);
//            die();
            if ($uploadImageArticle->image != null) {
                // этот метот сохраняет изображение в папке с id категории и занимается валидацией
                if ($uploadImageArticle->validate() && $uploadImageArticle->upload('article')) {

                    $modelArticle->image_name = $uploadImageArticle->image->name;
                    $modelArticle->save();
                    Yii::$app->session->setFlash('success', 'Данные приняты');
                    return $this->redirect(['/admin/article']);
                }
            } else {
                $uploadImageArticle->addErrors(['image' => 'загрузите обложку']);
            }

            Yii::$app->session->setFlash('danger', 'Ошибка записи');
            $openFormArticle = true;
            return $this->render('index', [
                'modelArticle' => $modelArticle,
                'searchModelArticle' => $searchModelArticle,
                'dataProviderArticle' => $dataProviderArticle,
                'uploadImageArticle' => $uploadImageArticle,
                'openFormArticle' => $openFormArticle,
            ]);

        }

        return $this->redirect('/admin/article');


    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {

        $uploadImageArticle = new UploadImage();
        $modelArticle = $this->findModel($id);


        if ($modelArticle->load(Yii::$app->request->post()) && $modelArticle->validate()) {

            $uploadImageArticle->image = UploadedFile::getInstance($uploadImageArticle, 'image');

            $oldImageName = $modelArticle->image_name;

            // если была загруженна новая картинка и успешно она загрузилась на сервер
            if (!empty($uploadImageArticle->image && $uploadImageArticle->upload('article'))) {
                // меняем в нашей модели Article поле image_name
                $modelArticle->image_name = $uploadImageArticle->image->name;
                // если была старая картинка удаляем
                if ($oldImageName != null) {
                    myDelete(Yii::getAlias('@uploads') . '/article/' . $oldImageName); // удаляем изображение с сервера
                }
            }else{
                // ошибка при обработке картинки фозвращаем форму
                Yii::$app->session->setFlash('danger', 'Ошибка загрузки обложки');
                return $this->render('update', [
                    'modelArticle' => $modelArticle,
                    'uploadImageArticle' => $uploadImageArticle,
                ]);
            }

            $modelArticle->update();
            // созданние одноразовых сообщений для пользователя(хранятся в сессии)
            Yii::$app->session->setFlash('success', 'Данные сохранены');
            return $this->redirect(['/admin/article']);
        }

        return $this->render('update', [
            'modelArticle' => $modelArticle,
            'uploadImageArticle' => $uploadImageArticle,
        ]);

    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $article = $this->findModel($id);
        myDelete(Yii::getAlias('@uploads') . '/article/' . $article->image_name); // удаляем изображение с сервера
        $article->delete();  // удаляем запись из базы данных
        Yii::$app->session->setFlash('success', 'Удаление прошло успешно');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

modules/admin/views/article/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use vova07\imperavi\Widget;
use yii\helpers\Url;
use kartik\file\FileInput;


/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin([
        'id' => 'article-form',
        'enableClientValidation' => true, // проверка на стороне клиента полностью,
        'method' => 'post',
        'action' => [$modelArticle->isNewRecord ? 'create' : 'update', 'id' => $modelArticle->id],
        'options' => ['enctype' => 'multipart/form-data'],
    ]); ?>

    <?php
    if (empty($modelArticle->data)) {
        $modelArticle->data = date('Y-m-d');
    }
    echo $form->field($modelArticle, 'data')->widget(DatePicker::className(), [
        'type' => DatePicker::TYPE_INPUT,
        'options' => ['placeholder' => 'Ввод даты ...'],
        'value' => date("yyyy-mm-dd", (integer)$modelArticle->data),
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'autoclose' => true,
            'todayHighlight' => true,// подсвечивает сегодняшнюю дату
//            'startView'=>2, // сначало выбираем год => 2
            'weekStart' => 1, //неделя начинается с понедельника
//            'startDate' => '01.05.2015 00:00', //самая ранняя возможная дата
            'todayBtn' => 'linked', //снизу кнопка "сегодня"
        ]

    ]);
    ?>

    <?= $form->field($modelArticle, 'title')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($modelArticle, 'description')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 100,
            'imageUpload' => Url::to(['article/save-redactor-img']),
            'imageManagerJson' => Url::to(['article/images-get']),
            'plugins' => [
                'clips',
                'fullscreen',
                'imagemanager',
                'fontsize',
                'fontcolor',
            ]
        ]
    ]); ?>


    <?php

    $pluginOptions = [
        'allowedFileExtensions' => ['jpg', 'gif', 'png', 'bmp'],
        'overwriteInitial' => true, // перезаписывает данные которые мы ему передали при инициализации
        'initialCaption' => $modelArticle->image_name,
        'showPreview' => true,
        'showCaption' => true,
        'showRemove' => false,
        'showUpload' => false,
    ];
    if (!empty($modelArticle->image_name)){
        $pluginOptions['initialPreview']=Html::img($modelArticle->image, ['style' => 'width:auto;height:auto;max-width:100%;max-height:100%;']);
        $pluginOptions['initialCaption']=$modelArticle->image_name;
    }
    echo $form->field($uploadImageArticle, 'image')->label('Обложка')->widget(FileInput::classname(), [
        'language' => 'ru',
        'options' => [
            'accept' => 'image/*',
            'required'=>$modelArticle->isNewRecord ? 'required' : false,
        ],
        'pluginOptions' => $pluginOptions
    ]); ?>


    <?= $form->field($modelArticle, 'is_active')->radioList([
        '1' => 'Вкл',
        '0' => 'Выкл',
    ], (($modelArticle->isNewRecord) ? ['value' => '1'] : [])) ?>

    <div class="form-group text-right">
        <?php if($modelArticle->isNewRecord ){
            echo Html::submitButton('Свернуть форму', ['id' => 'closeFormNewArticle', 'class' => 'btn btn-primary']);
        }  ?>
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php //if (!empty($modelArticle->image_name)): ?>
<!--    <div class="col-md-5">-->
<!--        <h5 class="text-center"><b>Обложка</b></h5>-->
<!--        <img src="--><?php //echo $modelArticle->image; ?><!--" alt="Изображение отсутствует" style="max-width:450px;">-->
<!--    </div>-->
<?php //endif; ?>

modules/admin/views/article/_gridView.php
<?php

use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Html;
use kartik\date\DatePicker;
use yii\widgets\LinkPager;
use yii\helpers\Url;

?>


<?php Pjax::begin(); ?>



<?= GridView::widget([
    'dataProvider' => $dataProviderArticle,
    'filterModel' => $searchModelArticle,
    'layout' => "{summary}\n{items}",
    'columns' => [

//        [
//            'attribute' => 'id',
//            'headerOptions' => ['width' => '40'],
//
//        ],
        [
            'attribute' => 'data',
            'contentOptions' => [
                'style' => 'min-width:100px;'
            ],
            'filter' => DatePicker::widget([
                'type' => DatePicker::TYPE_INPUT,
                'model' => $searchModelArticle,
                'attribute' => 'data',
                'language' => 'ru',
                'pluginOptions' => [
                    'autoclose' => true,
                    'minViewMode' => 'months',
                    'todayHighlight' => true,// подсвечивает сегодняшнюю дату
                    'startView' => 1, // сначало выбираем год => 2
                    'format' => 'yyyy-mm',
                    'clearBtn' => true,
                ],
            ]),

        ],

//        [
//            'attribute' => 'title',
//            'contentOptions' => [
//                'style' => 'min-width:250px;'
//            ]
//        ],
        ['attribute' => 'title',
            'format'=> 'html',
            'value' => function($data){
                return Html::a($data->title,Url::toRoute(['article/update', 'id' => $data->id]),['title'=>'Редактировать']);
            },
            'contentOptions' => [
                'style' => 'min-width:150px;'
            ]
        ],
        [
            'attribute' => 'description',
            'format' => 'raw',
//            'contentOptions' => ['class' => 'cell_class', 'style' => [
//            ]],
            'content' => function ($data) {
                $text = $data->description;
                if (strlen($text) > 300) {
                    return Html::tag('div', substr($text, 0, strpos($text, ' ', 300)) . ' ...', ['class' => ['div_class'], 'style' => [
                        // свойства каждого div
                    ]]);
                } else {
                    return Html::tag('div', $data->description, ['class' => ['div_class'], 'style' => [
                        // свойства каждого div
                    ]]);
                }

            },

        ],
        [
//            'headerOptions' => ['width' => '160'],
            'label' => 'Обложка',
            'format' => 'raw',
            'value' => function ($data) {
                return Html::a((Html::img($data->image, [
                    'alt' => 'Изображение отсутствует',
                    'style' => 'width:150px;'
                ])), [$data->image], ['class' => '', 'data-pjax' => "0",'title'=>'открыть']);

            },
        ],

        [
            'attribute' => 'is_active',
            'filter' => \app\models\Article::getStatusList(),
            'value' => 'status',
        ],

        [
            'class' => 'yii\grid\ActionColumn',
            'urlCreator' => function ($action, $model, $key, $index) {
                if ($action == 'view') {
                    return \yii\helpers\Url::to(['/article/' . $action, 'id' => $model->id]);
                }else{
                    return \yii\helpers\Url::to(['/admin/article/' . $action, 'id' => $model->id]);
                }
            }
        ],
    ],
]); ?>

    <div class="text-center">
        <?php echo LinkPager::widget([
            'pagination' => $dataProviderArticle->pagination,
        ]); ?>
    </div>


<?php Pjax::end(); ?>

modules/admin/views/article/_myGridView.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

?>


<div class="container-fluid container-articles  text-center">
    <div class="row table-striped table-bordered">
        <?php $prefix = ((empty(Yii::$app->request->get('sort')) or (Yii::$app->request->get('sort') == 'id')) ? '-' : ''); ?>
        <div class="col-md-1"><a href="/admin/article/index?sort=<?php echo $prefix; ?>id" data-sort="id">ID</a></div>
        <div class="col-md-2"><a href="/admin/article/index?sort=data" data-sort="data">Дата</a></div>
        <div class="col-md-4">Заголовок</div>
        <div class="col-md-2">Изображение</div>
        <div class="col-md-1 action-column">Статус</div>
        <div class="col-md-2 action-column">&nbsp;</div>
    </div>
    <div id="w1-filters" class="filters row table-bordered table-striped">
        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
        ]); ?>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-2"><?php echo $form->field($searchModel, 'data')->label(false) ?></div>
        <div class="col-md-4">&nbsp;</div>
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-1"><?php echo $form->field($searchModel, 'is_active')->dropDownList(\app\models\Article::getStatusList())->label(false) ?></div>
        <div class="col-md-2">
            <?php echo Html::submitButton('Search', ['class' => 'btn btn-primary']);
            ActiveForm::end() ?>
        </div>
    </div>


    <?php foreach ($articles as $article):; ?>


        <div class="row table-bordered">
            <?php echo $this->render('_updateForm', [
                'article' => $article,
                'uploadImage' => $uploadImage,
            ]); ?>
        </div>



    <?php endforeach; ?>
</div>

modules/admin/views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'data') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'image_name') ?>

    <?= $form->field($model, 'description') ?>

    <?php  echo $form->field($model, 'is_active') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/article/_updateForm.php
<?php

use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use yii\helpers\Html;

?>


<?php \yii\widgets\Pjax::begin(['id' => "pjax-id-$article->id",
    'timeout' => 5000,
//            'enablePushState' => true,
    'clientOptions' => ['method' => 'post'],
    'options' => [
        'data-pjax' => true,
    ]]); ?>

<?php $form = ActiveForm::begin([
    'id' => "article-form-id-$article->id",
    'enableAjaxValidation' => true,
    'enableClientValidation' => true, // проверка на стороне клиента полностью,
    'method' => 'post',
    'action' => ['update', 'id' => $article->id],
    'options' => [
        'class' => 'form-article _div_updateForm',
        'data-id' => $article->id,
    ],
]); ?>


<div class="col-md-1">
    <div class="form-control-static"><?php echo $article->id ?></div>
</div>

<div class="col-md-2" style=""><?php
    //                    if($article->data) {
    //                        $article->data = date("yyyy-mm-dd", (integer) $article->data);
    //                    }
    echo $form->field($article, 'data')->label(false)->widget(DatePicker::className(), [
        'type' => 2,
//            'options' => ['placeholder' => 'Ввод даты ...'],
        'value' => date("yyyy-mm-dd", (integer)$article->data),
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'autoclose' => true,
            'todayHighlight' => true,// подсвечивает сегодняшнюю дату
//            'startView'=>2, // сначало выбираем год => 2
            'weekStart' => 1, //неделя начинается с понедельника
//            'startDate' => '01.05.2015 00:00', //самая ранняя возможная дата
            'todayBtn' => 'linked', //снизу кнопка "сегодня"
        ]

    ]); ?>

</div>

<div class="col-md-4">
    <?= $form->field($article, 'title')->textInput(['maxlength' => true])->label(false) ?>

    <?= $form->field($article, 'description')->textarea(['rows' => 6, 'cols' => 70]) ?>
</div>

<div class="col-md-2"><?php
    echo Html::img('/' . $article->image, [
        'alt' => 'Изображение отсутствует',
//            'style' => 'width:200px;',
        'class' => 'img-responsive center-block img-thumbnail',
    ]); ?>

</div>


<div class="col-md-1">
    <?= $form->field($article, 'is_active')->radioList([
        '0' => 'off',
        '1' => 'on',
    ])->label(false);

     ActiveForm::end();
     \yii\widgets\Pjax::end(); ?>
    </div>

<div class="col-md-2">
    <div class="form-group">
<!--        --><?php //echo Html::submitButton('Сохранить', ['class' => 'btn btn-success',]) ?>
        <?php $formUp = ActiveForm::begin([
            'id' => "formUp-id-$article->id",
//            'enableAjaxValidation' => true,
//            'enableClientValidation' => true, // проверка на стороне клиента полностью,
            'method' => 'post',
            'action' => ['update', 'id' => $article->id],
            'options' => [
                'enctype' => 'multipart/form-data',
                'class' => 'form-article _div_updateImage',
                'data-id' => $article->id,
                'data-pjax'=>0,
            ],
        ]);
        echo $formUp->field($uploadImage, 'image')->fileInput([
            'data-pjax'=>0,
            'class' => "button-$article->id filestyle",
            'style' => 'display: block;',
            'data-buttonText' => 'New Image',
            'data-buttonName' => "btn-primary",
//                        'data-placeholder' => $modelImage->image_path,
        ])->label(false);


        echo Html::submitButton('Загрузить', ['class' => 'buttonAddImage btn btn-success ',
            'for'=>'formUp-id-$article->id',
//            'data-button-click' => "button-$article->id",
            'style' => '']);
        ActiveForm::end();  ?>

    </div>
</div>

modules/admin/views/article/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title = 'Создание событий';

?>
<div class="article-create">

<!--    <h1>--><?php //echo Html::encode($this->title) ?><!--</h1>-->

    <?= $this->render('_form', [
        'modelArticle' => $modelArticle,
        'uploadImageArticle' => $uploadImageArticle,

    ]) ?>

</div>

modules/admin/views/article/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\ListView;
use yii\widgets\LinkPager;

$this->registerJsFile('/js/admin/article/index.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerCssFile("/css/admin/article/index.css");

/* @var $this yii\web\View */
/* @var $searchModel app\models\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Настройка событий';

?>
<div class="article-index">

    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <?php if (Yii::$app->session->hasFlash('success')): ?>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php echo Yii::$app->session->getFlash('success'); ?>
                </div>
            <?php endif; ?>

            <!--    --><?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <div id="addArticle" style="display: <?php echo ($openFormArticle) ? 'block' : 'none'; ?>" class="row">
                <hr>
                <h2 class="text-center">Новое событие</h2>

                <?= $this->render('_form', [
                    'modelArticle' => $modelArticle,
                    'uploadImageArticle' => $uploadImageArticle,
                ]); ?>
            </div>

            <br>
        </div>
    </div>


    <div>
        <hr>
        <h2 class="text-center"><?= Html::encode($this->title) ?></h2>
        <p class="text-right">
            <?php echo Html::submitButton('Добавить событие', ['id' => 'openFormNewArticle', 'class' => 'btn btn-primary']) ?>
        </p>
        <?php echo $this->render('_gridView', [
            'dataProviderArticle' => $dataProviderArticle,
            'searchModelArticle' => $searchModelArticle,
        ]) ?>
    </div>


</div>

modules/admin/views/article/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $modelArticle->title;

?>
<div class="article-update row">
    <div class="col-md-8 col-md-offset-2">
        <hr>
        <?php echo Html::a('Вернутся к списку новостей', ['/admin/article'], ['class' => 'btn btn-primary text-left']) ?>
        <h2 class="text-center"><?= Html::encode($this->title) ?></h2>

        <?php if (Yii::$app->session->hasFlash('danger')): ?>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo Yii::$app->session->getFlash('danger'); ?>
            </div>
        <?php endif; ?>

        <?= $this->render('_form', [
            'modelArticle' => $modelArticle,
            'uploadImageArticle' =>$uploadImageArticle,
        ]) ?>
    </div>




</div>

modules/admin/views/article/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title = $model->title;

?>
<div class="article-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить событие?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'data',
            'title',
            'image_name',
            'description:ntext',
            'is_active',
        ],
    ]) ?>

</div>