modules/admin/controllers/CategoryController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Category;
use app\models\CategorySearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use app\models\Image;
use app\models\ImageSearch;
use app\models\UploadImage;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends AppAdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete-category' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();

//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider = $searchModel->search(Yii::$app->request->post()); // Pjax

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

//    /**
//     * Displays a single Category model.
//     * @param integer $id
//     * @return mixed
//     */
//    public function actionView($id)
//    {
//        return $this->render('view', [
//            'model' => $this->findModel($id),
//        ]);
//    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreateCategory()
    {
        $modelCategory = new Category();

        if ($modelCategory->load(Yii::$app->request->post()) && $modelCategory->save()) {
            mkdir(Yii::getAlias('@app') . '/web/uploads/images/' . $modelCategory->id, 0775, true);
            Yii::$app->session->setFlash('success', "Данные сохранены. Вернутся к <a href='/admin/category'>списку категорий</a>!"); // созданние одноразовых сообщений для пользователя(хранятся в сессии)
            return $this->redirect(['update-category', 'id' => $modelCategory->id]);
        } else {
            return $this->render('create-category', [
                'modelCategory' => $modelCategory,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateCategory($id)
    {
        $modelCategory = $this->findModel($id);
        $searchModelImage = new ImageSearch();
        $searchModelImage->id_category = $id;
        $categoryList = Category::getCategoriesList();
        $categoryListForFilter = ['' => 'Все'] + $categoryList;
        $dataProviderImage = $searchModelImage->search(Yii::$app->request->queryParams);// Pjax


        if ($modelCategory->load(Yii::$app->request->post()) && $modelCategory->save()) {
            Yii::$app->session->setFlash('success', "Данные сохранены. Вернутся к <a href='/admin/category'>списку категорий</a>!"); // созданние одноразовых сообщений для пользователя(хранятся в сессии)
            return $this->refresh();
        }

        return $this->render('update-category', [
            'modelCategory' => $modelCategory,
            'searchModelImage' => $searchModelImage,
            'dataProviderImage' => $dataProviderImage,
            'categoryList' => $categoryList,
            'categoryListForFilter' => $categoryListForFilter,
        ]);

    }


    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeleteCategory($id)
    {
        $this->findModel($id)->delete();
        myDelete(Yii::getAlias('@app') . '/web/uploads/images/' . $id);
        Yii::$app->session->setFlash('success', 'Данные успешно удалены'); // созданние одноразовых сообщений для пользователя(хранятся в сессии)
        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/category/_form-category.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use vova07\imperavi\Widget;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $modelCategory app\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="categories-form ">

    <?php $form = ActiveForm::begin(['method' => 'post']); ?>

    <?= $form->field($modelCategory, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelCategory, 'genre')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($modelCategory, 'description')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 100,
            'plugins' => [
                'clips',
                'fullscreen'
            ],
        ]
    ]); ?>
    <?= $form->field($modelCategory, 'is_active')->dropDownList(\app\models\Category::getStatusList(), (isset($status)) ? ['value' => '1'] : []) ?>

    <div class="form-group form-buttons">

        <div>
            <?php echo Html::a('Вернуться к списку категорий', ['/admin/category'], ['class' => 'btn btn-primary']) ?>

            <?php if (!$modelCategory->isNewRecord): ?>
                <?php echo Html::Button('Свернуть форму', ['class' => 'btn btn-primary', 'id' => 'close-form-category']); ?>
            <?php endif; ?>
        </div>


        <div>
            <?php if (!$modelCategory->isNewRecord): ?>
                <?php echo Html::a('Удалить', ['/admin/category/delete-category', 'id' => $modelCategory->id], ['class' => 'btn btn-danger']); ?>
            <?php endif; ?>
            <?php echo Html::submitButton($modelCategory->isNewRecord ? 'Создать' : 'Сохранить', ['class' => 'btn btn-success text-left']) ?>

        </div>


    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/category/_gridViewImage.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>

<?php \yii\widgets\Pjax::begin(['id' => 'filter-GridView',
    'timeout' => 5000,
    'enablePushState' => true, // подменять ли Url
    'options' => [
//        'data-pjax' => true,
    ],
]); ?>

<?= GridView::widget([
    'dataProvider' => $dataProviderImage,
    'filterModel' => $searchModelImage,
    'layout' => "{summary}\n{items}",

//        'viewParams' => [
//            '$categoryList' => $categoryList,
//        ],
    'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],

        [
            'attribute' => 'id',
            'value' => 'id',
            'headerOptions' => ['width' => '50'],
        ],
        [
            'attribute' => 'id_category',
            'label' => 'Категория',
            'format' => 'raw', // Возможные варианты: raw, html
            'value' => function ($data) use ($categoryList) {
                return $this->render('/image/_updateForm', [
                    'modelImage' => $data,
                    'categoryList' => $categoryList,
                ]);
            },
//                'headerOptions' => ['width' => '200'],
            'filter' => Html::dropDownList('ImageSearch[id_category]', $searchModelImage->id_category, $categoryListForFilter, ['class' => 'form-control']),
//                'filter' => $categoryList,
        ],
        [
            'attribute' => 'name_for_slider',
            'format' => 'raw',
            'value' => function ($data) {
                return $this->render('/image/_updateNameForm', [
                    'modelImage' => $data,
                ]);
            },
        ],
        [
            'attribute' => 'slider_up',
            'format' => 'raw',
            'filter' => Html::dropDownList('ImageSearch[slider_up]', $searchModelImage->slider_up, ['' => 'Все', 0 => 'Отключен', 1 => 'Активный',], ['class' => 'form-control']),
            'value' => function ($data) {
                $icon = ($data->slider_up == 1) ? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove';
                return Html::tag('span', '',
                    ['class' => $icon,
                        'title'=>"изменить",
                        'style'=>'cursor:pointer;',
                        'data-name' => 'slider_up',
                        'data-id' => $data->id,
                        'data-value' => $data->slider_up]);
            },
        ],
        [
            'attribute' => 'slider_down',
            'format' => 'raw',
            'filter' => Html::dropDownList('ImageSearch[slider_down]',
                $searchModelImage->slider_down,
                ['' => 'Все',
                    0 => 'Отключен',
                    1 => 'Активный'],
                ['class' => 'form-control']),
            'value' => function ($data) {
                $icon = ($data->slider_down == 1) ? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove';
                return Html::tag('span', '',
                    ['class' => $icon,
                        'title'=>"изменить",
                        'style'=>'cursor:pointer;',
                        'data-name' => 'slider_down',
                        'data-id' => $data->id,
                        'data-value' => $data->slider_down]);
            },
        ],
        [
            'headerOptions' => ['width' => '160'],
            'label' => 'Картинка',
            'format' => 'raw',
            'value' => function ($data) {
                return Html::a((Html::img('/' . $data->imagePath, [
                    'alt' => 'Изображение отсутствует',
                    'style' => 'width:150px;',
                    'title'=>'открыть'
                ])), ['/' . $data->imagePath], ['class' => '', 'data-pjax' => "0"]);

            },
        ],

        ['class' => 'yii\grid\ActionColumn',
//            'header' => 'Действия',
//            'headerOptions' => ['width' => '80'],
            'template' => '{delete}',
            'urlCreator' => function ($action, $model, $key, $index) {
                return \yii\helpers\Url::to(['/admin/image/' . $action . '', 'id' => $model->id]);

            }
        ],
    ],
]); ?>

<div class="text-center">
    <?php echo LinkPager::widget([
        'pagination' => $dataProviderImage->pagination,
    ]); ?>
</div>

<?php \yii\widgets\Pjax::end(); ?>

modules/admin/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="categories-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'post',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'genre') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'is_active') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/category/create-category.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $modelCategory app\models\Category */

$this->title = 'Создание новой категории для галлереи';
$this->registerCssFile("/css/admin/category/create-category.css");

?>
<div class="categories-create row">
    <div class="col-md-8 col-md-offset-2">
        <hr>
        <h2 class="text-center"><?= Html::encode($this->title) ?></h2>

        <br>


        <?= $this->render('_form-category', [
            'modelCategory' => $modelCategory,
            'status' => '1',
        ]) ?>


    </div>


</div>

modules/admin/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->registerCssFile("/css/admin/category/index.css");

$this->title = 'Настройка Галереи';

?>
<div class="categories-index">

    <hr>
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php echo Yii::$app->session->getFlash('success'); ?>
        </div>
    <?php endif; ?>

    <h2 class="text-center"><?= Html::encode($this->title) ?></h2>

    <p class="text-right">
        <?= Html::a('Добавить категорию', ['create-category'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?php \yii\widgets\Pjax::begin(['id' => 'category-pjax',
        'timeout' => false,
        'enablePushState' => false,
        'clientOptions' => ['method' => 'POST']]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],

//            'id',
            ['attribute' => 'name',
                'format'=> 'html',
                'value' => function($data){
                    return Html::a($data->name,Url::toRoute(['category/update-category', 'id' => $data->id]),['title'=>'Редактировать']);
                },
            ],
            [
                'attribute' => 'genre',
                'filter'=>\app\models\Category::getGenreList(),
                'value' => 'genre',
                'headerOptions' => ['width' => '200'],
            ],

            [
                'attribute' => 'description',
                'format'=> 'raw',
                'contentOptions' => ['class' => 'cell_class', 'style' => [

                ]],
                'content' => function ($data) {
                    $text = $data->description;
                    if (strlen($text) > 200) {
                        return Html::tag('div', substr($text, 0, 200) . '...', ['class' => ['div_class'], 'style' => [
                            // свойства каждого div
                        ]]);
                    } else {
                        return Html::tag('div', $data->description, ['class' => ['div_class'], 'style' => [
                            // свойства каждого div
                        ]]);
                    }
                },
            ],

            [
                'attribute' => 'is_active',
//                'value' => 'isActive',
//                'filter' => array('' => 'Все', "1" => "Вкл", "0" => "Выкл"),
                'filter' =>\app\models\Category::getStatusList(),
                'value'=>'status',
            ],

            [
                'class' => 'yii\grid\ActionColumn',
//                'header'=>'Действия',
//                'headerOptions' => ['width' => '80'],
                'template' => '{view} {update} {delete}',
                'urlCreator'=>function($action, $model, $key, $index){
                        if ($action=='view'){
                            return \yii\helpers\Url::to(['/gallery/' . $action, 'id' => $model->id]);
                        }else{
                            return \yii\helpers\Url::to(['' . $action . '-category', 'id' => $model->id]);

                        }
                }
            ],
        ],
    ]); ?>

    <?php \yii\widgets\Pjax::end(); ?>

</div>

modules/admin/views/category/update-category.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */
$this->registerJsFile('/js/admin/category/update-category.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]);

$this->registerCssFile("/css/admin/category/update-category.css");

$this->title = $modelCategory->name;

?>

<div class="category-update">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <hr>
            <?php if (Yii::$app->session->hasFlash('success')): ?>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php echo Yii::$app->session->getFlash('success'); ?>
                </div>
            <?php endif; ?>


            <h2 class="text-center"><?= Html::encode($this->title) ?></h2>

            <?php echo Html::Button('Развернуть форму категории', [
                'class' => 'btn btn-primary',
                'id' => 'open-form-category',
                'style' => 'display: none']); ?>

            <div class="categories-update-form">
                <?= $this->render('_form-category', [
                    'modelCategory' => $modelCategory,
                ]) ?>
            </div>
        </div>

    </div>


    <hr>
    <h2 class="text-center">Список изображений в категории <?php echo Html::encode($this->title) ?></h2>
    <p class="text-right">
        <?php echo Html::a('Добавить Изображение', ['/admin/image/create', 'categoryId' => $modelCategory->id], ['class' => 'btn btn-primary']); ?>
    </p>

    <div>
        <?php echo $this->render('_gridViewImage', [
            'dataProviderImage' => $dataProviderImage,
            'searchModelImage' => $searchModelImage,
            'categoryListForFilter' => $categoryListForFilter,
            'categoryList' => $categoryList,
            'categoryId' => $modelCategory->id,
        ]) ?>
    </div>
</div>

modules/admin/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Category;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $model->name;

?>
<div class="categories-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Вернутся к списку категорий', ['/admin/category'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Добавить изображение', ['/admin/image/create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить категорию?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'genre',
            'description:html',

            ['label' => 'Активность',
                'value' =>$model->getStatus()
                ],

        ],
    ]) ?>

</div>